services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    environment:
      - LLAMA_MODEL=${LLAMA_MODEL:-Llama-4-Maverick-17B-128E-Instruct-FP8}
      - LLAMA_TEMPERATURE=${LLAMA_TEMPERATURE:-0.1}
      - LLAMA_BASE_URL=${LLAMA_BASE_URL:-https://api.llama.com/compat/v1/}
      - ENABLE_STREAMING=${ENABLE_STREAMING:-true}
      - STREAM_CHUNK_SIZE=${STREAM_CHUNK_SIZE:-100}
      - REQUEST_TIMEOUT=${REQUEST_TIMEOUT:-300}
      - CONNECTION_TIMEOUT=${CONNECTION_TIMEOUT:-30}
      - MAX_CONCURRENT_REQUESTS=${MAX_CONCURRENT_REQUESTS:-10}
      - UPLOAD_DIR=${UPLOAD_DIR:-uploads}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-52428800}
      - CHUNK_SIZE=${CHUNK_SIZE:-1000}
      - CHUNK_OVERLAP=${CHUNK_OVERLAP:-200}
      - MAX_TOKENS_PER_REQUEST=${MAX_TOKENS_PER_REQUEST:-4000}
      - CHROMA_PERSIST_DIRECTORY=${CHROMA_PERSIST_DIRECTORY:-./chroma_db}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/chroma_db:/app/chroma_db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    depends_on:
      - backend
      - redis
    environment:
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - LLAMA_MODEL=${LLAMA_MODEL:-Llama-4-Maverick-17B-128E-Instruct-FP8}
      - LLAMA_TEMPERATURE=${LLAMA_TEMPERATURE:-0.1}
      - LLAMA_BASE_URL=${LLAMA_BASE_URL:-https://api.llama.com/compat/v1/}
      - UPLOAD_DIR=${UPLOAD_DIR:-uploads}
      - CHROMA_PERSIST_DIRECTORY=${CHROMA_PERSIST_DIRECTORY:-./chroma_db}
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/chroma_db:/app/chroma_db
    command: ["celery", "-A", "app.worker.celery_app", "worker", "--loglevel=INFO"]
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
    profiles:
      - production

volumes:
  uploads:
  chroma_db:
